
#AL INICIAR SE NOS DEBE PEDIR INGRESA UN NUMERO,SI ESTE ES MAYOR A 0 EL PROGRAMA INCIA,DE LO CONTRARIO FINALIZA (tambien si se ingresa otra cosa que no sea un numero)



num1 = 0

num2= int(input("INGRESE UN NUMERO (no se permite letras,palabras ni signos): "))

if num1<num2:
    print("¡BIENVENIDO! A COMENZADO SU PROGRAMA.")

else:
    print("SU PROGRAMA A FINALIZADO.")




#SE DEBE PODER INGRESAR UNA PALABRA O FRASE Y CONTAR CUANTOS CARACTERES TIENE DICHA PALABRA O FRASE



print ("EN ESTE PROGRAMA TAMBIEN PODES INGRESAR UNA PALABRA Y SABER LA CANTIDAD DE CARACTERES QUE TIENE.")

palabra =(input("INGRESE UNA PALABRA: "))

print("LA CANTIDAD DE CARACTERES QUE TIENE SU PALABRA SON: ",(len(palabra)))



#CON EL VALOR OBTENIDO EN EL PUTNTO ANTERIOR CALCULAR SU FACTORIAL



print("CON LA CANTIDAD DE CARACTERES PUEDE CALCULAR SU FACTORIAL Y SABER SI SU NUMERO ES PAR O NO")

numero=int(input("INGRESE SU NUMERO DE CARACTERES DEL PUNTO ANTERIOR: "))

factorial = 1

for n in range(1, (numero+1)):
    factorial = factorial * n

print( "EL FACTORIAL DE {0} ES: {1}".format(numero,factorial)) 



#UNA VEZ ECHO ESTO DECIR SI EL NUMERO ES PAR O IMPAR

numero = float(input("INGRESA EL RESULTADO QUE TE DIO DE TU FACTORIAL PARA SABER SI TU NUMERO ES PAR O IMPAR: "))

if numero % 2 == 0:
    
    print("SU NUMERO ES PAR")

else:
    print("SU NUMERO ES IMPAR")    




num1 = 0

num2= int(input("SI DESEA TERMNAR EL PROGRAMA PRECIONE 0(cero). SI DESEA CONTINUAR,PRECIONE UN NUMERO SUPERIOR: "))

if num1<num2:
    print("¡BIENVENIDO! A COMENZADO SU PROGRAMA.")

else:
    print("SU PROGRAMA A FINALIZADO.")



    #SE DEBE PODER INGRESAR UNA PALABRA O FRASE Y CONTAR CUANTOS CARACTERES TIENE DICHA PALABRA O FRASE



print ("EN ESTE PROGRAMA TAMBIEN PODES INGRESAR UNA PALABRA Y SABER LA CANTIDAD DE CARACTERES QUE TIENE.")

palabra =(input("INGRESE UNA PALABRA: "))

print("LA CANTIDAD DE CARACTERES QUE TIENE SU PALABRA SON: ",(len(palabra)))



#CON EL VALOR OBTENIDO EN EL PUTNTO ANTERIOR CALCULAR SU FACTORIAL



print("CON LA CANTIDAD DE CARACTERES PUEDE CALCULAR SU FACTORIAL Y SABER SI SU NUMERO ES PAR O NO")

numero=int(input("INGRESE SU NUMERO DE CARACTERES DEL PUNTO ANTERIOR: "))

factorial = 1

for n in range(1, (numero+1)):
    factorial = factorial * n

print( "EL FACTORIAL DE {0} ES: {1}".format(numero,factorial)) 



#UNA VEZ ECHO ESTO DECIR SI EL NUMERO ES PAR O IMPAR

numero = float(input("INGRESA EL RESULTADO QUE TE DIO DE TU FACTORIAL PARA SABER SI TU NUMERO ES PAR O IMPAR: "))

if numero % 2 == 0:
    
    print("SU NUMERO ES PAR")

else:
    print("SU NUMERO ES IMPAR")  
    
     



num1 = 0

num2= int(input("SI DESEA TERMNAR EL PROGRAMA PRECIONE 0(cero). SI DESEA CONTINUAR,PRECIONE UN NUMERO SUPERIOR: "))

if num1<num2:
    print("¡BIENVENIDO! A COMENZADO SU PROGRAMA.")

else:
    print("SU PROGRAMA A FINALIZADO.")  




 #SE DEBE PODER INGRESAR UNA PALABRA O FRASE Y CONTAR CUANTOS CARACTERES TIENE DICHA PALABRA O FRASE



print ("EN ESTE PROGRAMA TAMBIEN PODES INGRESAR UNA PALABRA Y SABER LA CANTIDAD DE CARACTERES QUE TIENE.")

palabra =(input("INGRESE UNA PALABRA: "))

print("LA CANTIDAD DE CARACTERES QUE TIENE SU PALABRA SON: ",(len(palabra)))



#CON EL VALOR OBTENIDO EN EL PUTNTO ANTERIOR CALCULAR SU FACTORIAL



print("CON LA CANTIDAD DE CARACTERES PUEDE CALCULAR SU FACTORIAL Y SABER SI SU NUMERO ES PAR O NO")

numero=int(input("INGRESE SU NUMERO DE CARACTERES DEL PUNTO ANTERIOR: "))

factorial = 1

for n in range(1, (numero+1)):
    factorial = factorial * n

print( "EL FACTORIAL DE {0} ES: {1}".format(numero,factorial)) 



#UNA VEZ ECHO ESTO DECIR SI EL NUMERO ES PAR O IMPAR

numero = float(input("INGRESA EL RESULTADO QUE TE DIO DE TU FACTORIAL PARA SABER SI TU NUMERO ES PAR O IMPAR: "))

if numero % 2 == 0:
    
    print("SU NUMERO ES PAR")

else:
    print("SU NUMERO ES IMPAR")    
   





  




